### PR TITLE
MediaConvert adapter has direct_output_lookup config, to avoid using CloudWatch

### PR DESCRIPTION
**Pull request by jrochkind**
MediaConvert adapter has direct_output_lookup config

To calculate output directly from the MediaConvert Job object, without requiring the CloudWatch logs.

(Also includes a commit that renamed some methods/variables for clarity, and added inline comments.)

All the info we were returning is there EXCEPT the actual output URLs. Sufficient info is there to calculate/predict the output URLs though -- I have done that for HLS. I believe it should be do-able for other formats too, but I am no
t familiar with them to figure out what they should be, so for NOW the URL calculation is only there for HLS. (If it's important, I could try to familiarize myself with the others and how the adapter currently handles them and try to match them without CloudWatch too? Not sure what other outputs are in any actual use at present, if any?)

This logic makes some assumptions, like that hteres only one input file and only one output group -- but I _think_ such assumptions were already being made, and the adapter at current is incapable of violating them. It does potentiall
y introduce some additional fragility though.

### CODE REVIEW

**Comment by jrochkind** [comment]
circleci does not seem to be kicking off, I don't know how to fix it. :(

**Review by mbklein — APPROVED** [review]
👍🏻

**Comment by mbklein** [comment]
I approved this because the PR looks good and the tests passed on my system. It would be great to get them passing in CI as well.

**Comment by jrochkind** [comment]
I believe @cjcolvar can make them run somehow. Pretty please then we'll merge after pass?

**Pull request merged**
