### PR TITLE
Update bixby to latest, with rubocop to more recent

### PR DESCRIPTION
**Pull request by jrochkind**
The latest bixby with more recent rubocop resulted in lots of violations. I had rubocop fix the all with --auto-correct. It's a lot of files... if tests still pass I guess we're good? Not sure. 

I was able to remove the rubocop exclusions @mbklein added in #90, they no longer apply. 

I had to add an exclusion having to do with the Rakefile; new rubocop didn't like the weird old setup involving `task 'environment' do`, but I didn't want to get into totally understanding what that did or how to safely change it, so I just excluded the test.

### CODE REVIEW

**Review by cjcolvar — APPROVED** [review]
This looks great!  Thanks @jrochkind !

**Comment by jrochkind** [comment]
Oops, now that I look over the diff myself, I'm feeling less sure about some of these changes. 

Per rubocop rules, this PR changed all the controllers from `< ActionController::Base` to `< ApplicationController`, and jobs from ` < ActiveJob::Base` to `< ApplicationJob`, models from `< ActiveRecord::Base` to ` < ApplicationRecord`. 

Now that I think about it... IS that appropriate for engine-provided controllers/models/jobs like that?  I'm not sure. 

I wonder if we should change it back and just disable those rubocop rules?  Thoughts @cjcolvar ? Sorry, I should have paid more attention before PR'ing it, I didn't realize those were some of the changes I was just like "lots of rubocop changes, tests are passing, i'm not paying attention." :(

**Comment by cjcolvar** [comment]
I wasn't sure about those either at first, but I think it is correct.  I think these super classes are defined by rails so they will exist even if the application doesn't define them.  This seems like a good change since it would allow the application to make modifications when they weren't able to before.

**Comment by jrochkind** [comment]
OK, cool, if you reviewed and determined that, we'll find out!

**Pull request merged**
